projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
      prepare-binding:
        output: src/generated/api.ts
        generator: binding-ts
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
      codegen:
        generator: prisma-binding
        language: typescript
        output:
          binding: src/generated/prisma.ts
